[package]
name = "polywrap_datetime_plugin"
version = "0.0.1-beta.3"
license = "MIT"
description = "Polywrap rust datetime plugin"
edition = "2021"

[dependencies]
polywrap_core = { version = "0.1.6-beta.5" }
polywrap_plugin = { version = "0.1.6-beta.5" }
polywrap_msgpack = { version = "0.1.6-beta.5" }
polywrap_resolvers = { version = "0.1.6-beta.5" }
wrap_manifest_schemas = { version = "0.1.6-beta.5" }

chrono = "0.4"
serde = {version = "1.0.145", features = ["derive"]}

[dev-dependencies]
polywrap_client = { version = "0.1.6-beta.5" }
