name: datetime-plugin-swift-ci

on:
  pull_request:
    paths:
      - "implementations/swift/**"

jobs:
  ci:
    name: datetime-plugin-swift-ci
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: swift test
        working-directory: ./implementations/swift